apiVersion: v1
kind: Pod
metadata:
  name: quota-mem-cpu-demo
spec:
  containers:
  - name: quota-mem-cpu-demo-ctr
    image: nginx
    resources:
      limits:
        memory: "50Mi"
        cpu: "80m"
      requests:
        memory: "50Mi"
        cpu: "40m"
